### ISSUE TITLE
MILESTONE - Environment Setup

### ISSUE THREAD

**Issue by xfrehner12** [cs481-ekh/f21-welolo#1]
Each team member will have each of their environments setup and functional to be approved by another team member as specified in the first milestone located in the Project Plan document. In addition to having each team member's local environments setup, we will also have test merchants data configured to be used with the application.

In the first week, we should also have a very simple test web application running that will be used to test basic functionality of the application. This will include:
- [ ] Payment form (recipient name, recipient number, message, amount ($))
- [ ] Payment Verification page
- [ ] Payment Failed page
- [ ] Receive funds page
