### ISSUE TITLE
MILESTONE - Integrate Payment API

### ISSUE THREAD

**Issue by ZahraRahmani2** [cs481-ekh/f21-welolo#9]
Acceptance Critria:

- [ ] As a web developer, when we don't have a clear understanding of the PayPal API, then we need to do a research how to use the PayPal API
- [ ] As a web developer, when there is no connection between PayPal sandbox with app, then we need to connect PayPal sandbox to app
- [ ] As a web developer, when there is no contact form, then we need to create a screen for recipient contact information
- [ ] As a web developer, when there is no payment form, then we need to create a screen for recipient payment information
- [ ] As a web developer, when there is no connection between payment screen to the backend, then we need to connect the payment screen to the backend
- [ ] As a web developer, when there is no connection between information screen and backend, then we need to connect the contact information screen to backend
- [ ] As a web developer, when we don't have PayPal API integrated with backend, then we need to Integrate PayPal API into the backend of the app
